% R bootcamp, Module 0: Recruit processing
% August 2016, UC Berkeley
% Chris Paciorek

# A few administrative things

## Where to find stuff

The Piazza site ([https://piazza.com/berkeley/summer2016/rbootcamp2016/home](https://piazza.com/berkeley/summer2016/rbootcamp2016/home)) is the main site for the bootcamp. It has information on logistics, software installation, and the Q&A area for online questions.  

The Github site ([https://github.com/berkeley-scf/r-bootcamp-2016](https://github.com/berkeley-scf/r-bootcamp-2016)) is updated more frequently (sometimes in real time) and is the master repository for materials for the modules; you can also get the individual files from Github. Instructions for accessing the materials on Github are on the Piazza site.

If you have an administrative question, email r-bootcamp@lists.berkeley.edu.

## Wireless

If you need wireless access as a guest (i.e., you don't have a CalNet ID), connect to 'CalVisitor'.

# A little warm-up

This isn't really all that related to R, programming or statistics, but check out the 'binary solo' in this [Flight of the Conchords song](https://www.youtube.com/watch?v=B1BdQcJ2ZYY).

# How we'll operate

The bootcamp will be organized in modules, each of which will be a combination of lecture/demo presentation concluded by a breakout session in which you'll work on a variety of problems of different levels of difficulty. The idea is for each person to find problems that challenge them but are not too hard. Solutions to the breakout problems will be presented before the start of the next module. 

Many of the modules will use a common dataset as an example on which to carry out various operations. We'll focus on a dataset of on-time information for US airline flights, 1987-2008 provided by the US government's Bureau of Transportation Statistics. This dataset is available in its entirety [here](http://stat-computing.org/dataexpo/2009/the-data.html). However, it's about 3.5 Gb compressed, so we'll work with a subset of just flights departing from SFO for 2005-2008, available in the Github repository as *airline.csv*. (Note that this is the full population of such flights -- I'll fit some statistical models but the interpretation is tricky as we are not working with a sample from a well-defined population.)
There's also a smaller subsample of the SFO flights in *airlineSubsample.csv* - you can use that in place of *airline.csv* if *airline.csv* is taking a while to load into R on your machine.

Counselors will be available to help answer any questions you have (just wave to one of them), or feel free to just ask the presenter during the presentation. The counselors will also be monitoring the [Piazza Q&A area](https://piazza.com/berkeley/summer2016/rbootcamp2016/home), so feel free to type in a question there and one of the counselors will answer the question. Or if you know the answer, help us out by answering it yourself or adding your thoughts. 

Your counseloRs are: Kellie Ottoboni (Statistics/BIDS), Rochelle Terman (Political Science/D-Lab), Chris Kennedy (Political Science/D-Lab), Evan Muzzall (Biology/D-Lab), Alex Padron (Biology), and Lauren Ponisio (ESPM/BIDS).

# Suggestions on how to get the most out of the bootcamp

I encourage you to:

- try out the code as we walk through it
-  keep your eyes open! -- We'll illustrate a lot of syntax and concepts by example
- try to guess what the syntax means in cases we haven't yet seen that syntax
- play with it and try variations and try to break it and see what happens
- tell us if something interesting happens as you experiment, or post a comment in the chat room
- ask questions of me, the counselors, and in the chat room

This is a bootcamp. So there may be some pain involved! If you find yourself not following everything, that's ok. You may miss some details, but try to follow the basics and the big picture. 

A few additional thoughts on my pedagogical philosophy here:

- I want to expose you to a lot of tools and ideas that you can come back to when you need them and when you have time for more depth.
- My aim is not to show you how to use specific statistical methods or analysis techniques. My goal is to get you up to speed generally in R.
- It can be hard to absorb everything in such a concentrated situation. Hopefully the material presented will be useful to you over the longer-term as you do more work with R.

# RStudio and R Markdown

We'll present most of the material from within RStudio, using R Markdown documents with embedded R code. R Markdown is an extension to the Markdown markup language that makes it easy to write HTML in a simple plain text format.  This allows us to both run the R code directly as well as compile on-the-fly to an HTML file that can be used for presentation. All files will be available on [Github](https://github.com/berkeley-scf/r-bootcamp-2016).  

Note: The files named *moduleX_blah_slides.html* have individual slides, while the files named *moduleX_blah.html* have the same content but all on one page.

Warning: in some cases the processing of the R code in the R Markdown is screwy and the slides have error messages that do not occur if you just run the code directly in R or RStudio. 

# Using Github to get the documents

To download the files from Github, you can do the following. 

## Within RStudio

Within RStudio go to File->New Project->Version Control->Git and enter:

- "Repository URL": https://github.com/berkeley-scf/r-bootcamp-2016
- "Project Directory Name": r-bootcamp-2016 (or something else of your choosing)
- "Directory": ~/Desktop (or somewhere of your choosing)

Then to update from the repository to get any changes we've made, you can select (from within RStudio):
Tools->Version Control->Pull Branches

or from the Environment/History/Git window, click on the Git tab and then on the blue down arrow.

Be warned that you probably do not want to make your own notes or changes to the files we are providing. Because if you do, and you then do a "Git Pull" to update the materials, you'll have to deal with the conflict between your local version and our version. You probably will want to make a personal copy of such files in another directory or by making copies of files with new names.

## From a Mac/Linux terminal window

Run the following commands:

- `cd /directory/where/you/want/repository/located`
- `git clone https://github.com/berkeley-scf/r-bootcamp-2016`

Then to update from the repository to get any changes we've made:

- `cd /directory/where/you/put/the/repository/r-bootcamp-2016`
- `git pull`


# What is R?

- R is an Open Source (and freely available) environment for statistical computing and graphics
- It is a full-featured programming language, in particular a scripting language (with similarities to Matlab and Python)
- It can be run interactively or as a batch/background job
- R is being actively developed with ongoing updates/new releases
- R has a variety of built-in as well as community-provided packages that extend its functionality with code and data; see [CRAN](http://www.cran.r-project.org) for the thousands of add-on packages
- It is freely-available and modifiable 
- Available for Windows, Mac OS X, and [Linux](http://dilbert.com/strips/comic/1995-06-24/)


# Modes of using R

- Using the RStudio GUI, an 'integrated development environment'
- From the command line in a Linux/Mac terminal window
- Running an R script in the background on a Linux/Mac machine (Windows?)
- Using the Windows/Mac GUIs



# Starting R and RStudio

The pieces of an R session include:

- The R console
- Scripts containing your code
- Help files
- Graphics windows
- Workspace containing your objects, which hold data and information

RStudio provides an integrated development environment in which all of these pieces are in a single application and tightly integrated, with a built-in editor for your code/scripts. 

# Why R?

- R is widely used (statisticians, scientists, social scientists) and has the widest statistical functionality of any software
- Users add functionality via packages all the time
- R is free and available on all major platforms
- As a scripting language, R is very powerful, flexible, and easy to use
- As a scripting language, R allows for reproducibility and automating tasks
- As a language, R can do essentially anything
- Wide usage helps to improve quality and reduce bugs
- R can interact with other software, databases, the operating system, the web, etc.
- R is built on C and can call user-written and external C code and packages (in particular, see the *Rcpp* R package)

# Why Not R?

* Other software is better than R at various tasks
    
    E.g., [Python](http://imgs.xkcd.com/comics/python.png) is very good for text manipulation, interacting with the operating system, and as a glue for tying together various applications/software in a workflow
* R can be much slower than compiled languages (but is often quite fast with good coding practices!)
* R's packages are only as good as the person who wrote them; no explicit quality control
* R is a sprawling and unstandardized ecosystem

# What are my other options? Get me out of here!

- Python
- Matlab/Octave
- Julia
- C/C++
- SAS
- Stata

# My hidden agenda 

In addition to learning some R, this workshop will expose you to a way of thinking about doing your computational work. 

The building blocks of scientific computing include:

- scripting
- reproducibility
- automating repetitive tasks
- version control (note our basic use of Git)


# The Legal Stuff

- Some of this material was drawn from [Jared Knowles R bootcamp](http://jaredknowles.com/r-bootcamp/url).
- Contributions from Kellie Ottoboni, Rochelle Terman, Chris Krogslund, and Jarrod Millman. Thank you!!!
- You are free to use, modify and redistribute any of this material with or without attribution, but if you use chunks of material, I'd appreciate a call-out.
