% R bootcamp, Breakout Solutions
% August 2016, UC Berkeley
% Chris Paciorek

```{r chunksetup, include=FALSE, cache=TRUE} 
# include any code here you don't want to show up in the document,
# e.g. package and dataset loading
if(Sys.getenv('USER') == 'paciorek') rm(list = ls())
if(!('modules' %in% unlist(strsplit(getwd(), split = '/')))) setwd('modules')
air <- read.csv('../data/airline.csv', stringsAsFactors = FALSE)
```

# Module 1: Basics


```{r basics1}
## 1 ##
x <- mean(air$DepDelay, na.rm = TRUE)

## 2 ##
# help(round)
round(x, digits = 2)
round(x, digits = 0)

## 3 ##
kmsPerMile <- 1.60934
dist_km <- air$Distance * kmsPerMile
c(dist_km[1], air$Distance[1])

## 4 ##
delayWorsening <- air$DepDelay < air$ArrDelay
head(delayWorsening)
```

```{r using_the_ideas1}
## 5 ##
summary(air$ArrDelay - air$DepDelay)

## 6 ##
delay <- air$DepDelay
delay[delay < 0] <- 0  
delay[delay > 60] <- 60
hist(delay)
hist(delay, nclass = 100)
hist(delay, nclass = 5)

## 7 ##
sub <- air[air$Dest == "ORD" | air$Dest == "IAH", ]
plot(sub$CRSDepTime, sub$DepDelay, main = 'Departure delay by time of day')
sub$color <- "blue"
sub$color[sub$Dest == "IAH"] <- "red"
plot(sub$CRSDepTime, sub$DepDelay, col = sub$color, 
                     main = 'Departure delay by time of day')

## 8 ##
y <- rnorm(10)
x <- rnorm(10)
mod <- lm(y ~ x)
summ <- summary(mod)
r2 <- summ$r.squared
rse <- summ$sigma
```

```{r advanced1}
## 9 ##
sub <- air[air$Dest == "ORD" | air$Dest == "IAH", ]
sub$color <- "blue"
sub$color[sub$Dest == "IAH"] <- "red"
daysInMonth <- c(31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)
cumDays <- c(0, cumsum(daysInMonth))
sub$julian <- (sub$Year - 2005)*365 + cumDays[sub$Month] + sub$DayofMonth
plot(sub$julian, sub$DepDelay, col = sub$color)

## 10 ##
plot(sub$julian, sub$DepDelay, col = sub$color, cex = 0.4, las = 1)
legend("topleft", legend = c('IAH', 'ORD'), col = c('red', 'blue'), cex = 0.4,
  pch = 1)
```


# Module 2: Managing R and R resources

```{r, basics2}
## 1 ##
install.packages('lmtest', repos = 'http://cran.cnr.berkeley.edu')

## 2 ##
getwd()
```

```{r, using_the_ideas2}
## 3 ##
curdir <- getwd()
system('cp ../data/cpds.csv ~/Downloads')  # accessing system calls within R (won't work in Windows)
setwd('~/Downloads')  # setwd('C:\\Users\\Your_Username\\Downloads')
cpds <- read.csv('cpds.csv')
setwd('~/Desktop')  # setwd('C:\\Users\\Your_Username\\Desktop')
write.csv(cpds, file = 'new_cpds.csv', row.names = FALSE, quote = FALSE)

## 4 ## 
pdf('test1.pdf')
hist(air$DepDelay[1:10000])
dev.off()

pdf('test2.pdf', height = 2, width = 2)
hist(air$DepDelay[1:10000])
dev.off()

## 5 ##
library(graphics)
library(maps)
searchpaths()

setwd(curdir)
```

```{r, advanced2}
## 6 ##
library(spam)
backsolve
base::backsolve
search()
```

# Module 3: Working with objects and data

```{r, basics3}
## 1 ##
air[5, ]

## 2 ##
air[ nrow(air) , ]

## 3 ##
sum(is.na(air$DepDelay))

## 4 ## 
air$DepDelay[ air$DepDelay > 300 ] <- NA

## 5 ##
paste(air$UniqueCarrier[1], air$FlightNum[1], sep = "-")
```

```{r, using_the_ideas3}
## 6 ##
paste("There are ", nrow(air), " rows in the dataset.", sep = "")

## 7 ##
air[ nrow(air), ]

## 8 ##
shortSW <- air$UniqueCarrier == "WN" & air$Distance < 1000
mean(shortSW)   # sum(shortSW) / length(shortSW)

## 9 ##
sub <- air[ shortSW , ]

## 10 ##
attributes(air)
names(attributes(air))
class(attributes(air))
```

```{r, advanced3}
## 11 ##
numArr <- sort(table(air$Dest), decreasing = TRUE)
air$Dest <- factor(air$Dest, levels = names(numArr)) 
# relevel(air$Dest, names(numArr))
boxplot(DepDelay ~ Dest, data = air, subset = Month == 1 & Year == 2005)

## 12 ##
nm <- paste(air$Year, air$Month, air$DayofMonth, air$UniqueCarrier, air$FlightNum, sep = "-")
attributes(air)$row.names <- nm
```

# Module 4: Calculations

```{r, basics4}
## 1 ##
air$Route <- paste(air$Origin, air$Dest, sep = "-")
head(air$Route)

## 2 ##
table(air$Year)
```

```{r, using_the_ideas4}
## 3 ##
sapply(air, function(x) sum(is.na(x)))

## 4 ##
carriers <- read.csv('../data/carriers.csv')
air2 <- merge(air, carriers, by.x = 'UniqueCarrier', by.y = 'Code', all.x = TRUE, all.y = FALSE)

## 5 ##
range(air$Dist)
air$Dist_binned <- cut(air$Distance, breaks = c(-Inf, 100, 500, 1000, 1500, 2000, Inf)) 
table(air$Dist_binned)

## 6 ##
boxplot(DepDelay ~ Dist_binned, data = air, ylim = 200)

## 7 ##
tmp <- air[order(air$Distance), ]
tmp[1, ]
air[which.min(air$Distance), ]

## 8 ##
y <- matrix(sample(1:10, 12, replace = TRUE), 
nrow = 3, ncol = 4)

## 8b ##
yidot <- rowSums(y)
ydotj <- colSums(y)
e <- outer(yidot, ydotj) / sum(y)

## 8a ##
chi2 <- sum( (y - e)^2 / e)
# chi2 <- sum(colSums( (y-e)^2 / e ))
```

```{r, advanced4}
## 9 ## 
aggregate(air$DepDelay, by = list(air$UniqueCarrier, air$Month, air$DayOfWeek), 
quantile, probs = 0.95, na.rm = TRUE)

## 10 ##
h <- air$DepTime %/% 100
m <- air$DepTime %% 100
h <- as.character(h)
h[nchar(h) == 1] <- paste('0', h[nchar(h) == 1], sep = '')
air$DepTimeChar <- paste(h, m, sep = '-')

air$Hour <- as.numeric(sapply(strsplit(air$DepTimeChar, '-'), '[', 1))
air$Minute <- as.numeric(sapply(strsplit(air$DepTimeChar, '-'), '[', 2))
minutesPerHour <- 60
air$DayMinutes <- (air$Hour-1)*minutesPerHour + air$Minute
hist(air$DayMinutes)
```

# Module 5: Useful stuff

```{r, basics5}
library(plyr)

## 1 ##
gap_median_lifeExp <- gapminder %>%
    group_by(continent) %>%
    summarize(med_lifeExp = median(lifeExp))

## 2 ## 
gapminder_pop_continent <- gapminder %>%
    group_by(continent, year) %>%
    mutate(continent_pop = sum(pop))

## 3 ##
gap_rel_gdp <- gapminder %>%
    group_by(continent, year) %>%
    mutate(gdpPercap_diff = gdpPercap - mean(gdpPercap)) %>%
    ungroup() %>%
    arrange(desc(gdpPercap_diff))

## 4 ##
gap_wider <- gap_rel_gdp %>% 
  select(country, year, gdpPercap_diff) %>% 
  spread(year, gdpPercap_diff)

## 5 ##
reg1 <- glm(formula = gdpPercap ~ lifeExp + pop + year, 
                family=gaussian, data=gapminder)

reg2 <- glm(formula = gdpPercap ~ lifeExp + pop + factor(year), 
                family = gaussian, data = gapminder)

## 6 ## 
gap_rel_gdp_sign <- gap_rel_gdp %>%
  mutate(sign = ifelse(gdpPercap_diff > 0, 1, 0))

reg_logit <- glm(formula = sign ~ lifeExp + pop, 
                family = binomial(link = "logit"), data = gap_rel_gdp_sign)
```

# Module 6: Programming

```{r, basics6}
## 1 ##
threshZero <- function(x) {
   x[x < 0] <- 0
   return(x)
}
```

```{r, using_the_ideas6}
## 2 ##
thresh <- function(x, threshold = 0, below = TRUE) {
    if(below) {
       x[ x < threshold ] <- threshold
    } else {
       x[ x > threshold ] <- threshold
    }
    return(x)
}

## 3 ##
thresh <- function(x, threshold = 0, below = TRUE) {
    if(!is.numeric(x) || is.list(x)) stop("'x' must be a numeric vector")
    if(below) {
       x[ x < threshold ] <- threshold
    } else {
       x[ x > threshold ] <- threshold
    }
    return(x)
}

## 4 ##
colSort <- function(data, col1, col2) {
    ord <- order(data[, col1], data[, col2], decreasing=TRUE)
    sorted <- data[ord, ]
    invisible(sorted)
}
```

```{r, advanced6}
## 5 ##
colSort <- function(data, ...) {
    ord <- order(..., decreasing=TRUE)
    sorted <- data[ord, ]
    invisible(sorted)
}

## 6 ##
colSort <- function(data, ..., cols = NULL, decreasing = FALSE) {
   if(is.null(cols)) {
      ord <- order(..., decreasing = decreasing)
   } else {
     if((!is.numeric(cols) && !is.character(cols)) || is.list(cols))
        stop("'cols' must be a numeric or character vector")
     if(is.numeric(cols) && max(cols) > ncol(data) ||
        is.character(cols) && any(!cols %in% names(data)))
           stop("'cols' refers to non-existent column")
      ord <- do.call(order, data[ , cols])
   }
   sorted <- data[ord, ]
   invisible(sorted)
}

## 7 ##
funGenerator <- function(x) {
   x <- 10
   g <- function(y) {
      return(x + y)
   }
   return(g)
}

x <- 2
f <- funGenerator()
f(1)

ls(environment(f))
environment(f)$x
```

# 7) Module 7: Core tools

```{r, basics7}
## 1 ##
popMean <- 5
x <- rpois(100, popMean)
mean(x) - popMean

## 2 ##
qchisq(0.95, 1)

## 3 ##
1 - pnorm(5)  # pnorm(5, upper.tail = TRUE)
1 - pt(5, df = 1)
```

```{r, using_the_ideas7}
## 4 ##
nBoot <- 500
vals <- rep(0, nBoot)

for(i in seq_len(nBoot)) { 
      smp <- sample(seq_len(nrow(air)), replace = TRUE) 
      vals[i] <- mean(air$DepDelay[smp], na.rm = TRUE)
}
hist(vals)
se <- sd(vals)
n <- sum(!is.na(air$DepDelay))
se_norm <- sd(air$DepDelay, na.rm = TRUE) / sqrt(n)

## 5 ##
DestSubset <- c('LAX','SEA','PHX','DEN','MSP','JFK','ATL','DFW','IAH', 'ORD') 
airSmall <- subset(air, Dest %in% DestSubset)
airSmall$DepDelayCens <- censor(airSmall$DepDelay, 180)
airSmall$SchedDepCont <- airSmall$CRSDepTime %/% 100 + (airSmall$CRSDepTime %% 100) / 60
mod_LAX <- gam(DepDelayCens ~ s(Month, k = 10) + s(SchedDepCont, k = 10), 
         data = airSmall, subset = airSmall$Dest == "LAX")
par(mfrow = c(1, 2))
plot(mod_LAX)
```

```{r, advanced7}
## 6 ## 
nFolds <- 10
n <- nrow(air)
fold_size <- rep(round(n / nFolds), nFolds)
fold_size[nFolds] <- n - (nFolds - 1)*fold_size[1]

fold <- rep(1:nFolds, times = fold_size)
table(fold)
set.seed(0)
air$Fold <- sample(fold, replace = TRUE)

## 7 ##
n <- 100
nReps <- 10000
data <- matrix(rpois(n*nReps, 3), ncol = nReps)
mns <- colMeans(data)
par(mfrow = c(1, 2))
hist(mns)
qqnorm(mns)
```

# Module 8: Graphics

```{r, basics8}
sub <- air[sample(1:nrow(air), 10000, replace = FALSE), ]

## 1 ##
sub$DepDelay[sub$DepDelay < 0] <- 0
sub$DepDelay[sub$DepDelay >= 60] <- 60 

ggplot(data = sub, aes(x = DepDelay)) + geom_histogram()

## 2 ##
ggplot(data = sub, aes(x = DepDelay, y = ArrDelay)) + geom_point() 

## 3 ##
pdf('delays.pdf')
ggplot(data = sub, aes(x = DepDelay, y = ArrDelay)) + geom_point() + 
  ggtitle("Arrival vs. Departure Delay") + xlab(label = "Departure delay (minutes)") +
  ylab(label = "Arrival delay (minutes)")
dev.off()

## 4 ##
ggplot(data = sub, aes(x = factor(DayOfWeek), y = DepDelay)) + geom_boxplot()
```

```{r, using_the_ideas8}
## 5 ##
DestSubset <- c('LAX','SEA','PHX','DEN','MSP','JFK','ATL','DFW','IAH', 'ORD')
ggplot(data = sub[sub$Dest %in% DestSubset, ], aes(x = factor(DayOfWeek), y = DepDelay)) + geom_boxplot() + facet_wrap(~Dest, nrow = 2, ncol = 5)

## 6 ##
ggplot(data = sub[sub$Dest %in% c('IAH', 'ORD'), ], aes(x = CRSDepTime, y = ArrDelay, color = Dest)) + geom_point() + scale_x_continuous(limits = c(600, 2400)) + scale_y_continuous(limits = c(-10, 120))
```

```{r, advanced8}
## 7 ##
DestSubset <- c('LAX','SEA','PHX','DEN','MSP','JFK','ATL','DFW','IAH', 'ORD')
ggplot(data = sub[sub$Dest %in% DestSubset, ], aes(x = CRSDepTime, y = DepDelay)) + geom_point(alpha = 0.3) + geom_smooth(method = "loess", color = 'red', se = FALSE) + scale_x_continuous(limits = c(600, 2400)) + facet_wrap(~Dest, nrow = 2) + theme_bw()
```


